version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=Password123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - app-network

  dockerapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: dcardenasa09/dockerapi:v2
    container_name: dockerapi
    ports:
      - "3510:3510"
    depends_on:
      - sqlserver
    networks:
      - app-network
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:3510"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=backend-api-db;User=sa;Password=Password123;TrustServerCertificate=True;"

  dockerfront:
    image: dcardenasa09/dockerfront:v1
    container_name: dockerfront
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
